stages: 
  - lint
  - test
  - build
  - publish

before_script:
  - python -V  # Print out python version for debugging

lint:
  image: python:3.10.8-alpine3.16
  stage: lint
  script:
    - pip install -r requirements.txt
    - pip install pylint
    - pylint app/main.py 

test:
  image: python:3.10.8-alpine3.16
  stage: test
  script: 
    - pip install -r requirements.txt
    - pip install pytest
    - pytest app/tests/test_main.py

build: 
  image: docker:24
  stage: build
  script:
    - docker build --network host -t europe-north1-docker.pkg.dev/css-markuslippo-2023/exercise-cicd/courses-api:v1 .
  before_script:
    - docker version
    - apk add --no-cache py3-pip
    - pip install -r requirements.txt

publish:
  image: docker:24
  stage: publish
  services:
    - docker:dind
  script: 
    - echo "$GCP_CREDENTIALS" > key.json 
    - docker login -u _json_key --password-stdin europe-north1-docker.pkg.dev/css-markuslippo-2023/exercise-cicd < key.json
    - docker push europe-north1-docker.pkg.dev/css-markuslippo-2023/exercise-cicd/courses-api:v1
