stages: 
  - lint
  - test
  - build
  - publish

before_script:
  - python -V  # Print out python version for debugging

lint:
  image: python:3.10.8-alpine3.16
  stage: lint
  script:
    - pip3 install pylint
    - pylint main.py
  before_script:
    - pip install -r requirements.txt

test:
  image: python:3.10.8-alpine3.16
  stage: test
  script: 
    - pip3 install pytest
    - pytest
  before_script:
    - pip install -r requirements.txt

build: 
  image: docker:24
  stage: build
  script:
    - docker build --network host -t europe-north1-docker.pkg.dev/css-markuslippo-2023/exercise-cicd/courses-api:v1 .
  before_script:
    - pip install -r requirements.txt

publish:
  image: docker:24
  stage: publish
  services:
    - docker:dind-24
  before_script:
    - echo $GCP_CREDENTIALS > gcp-key.json
    - cat gcp-key.json | docker login -u _json_key --password-stdin europe-north1-docker.pkg.dev
  script:
    - docker push europe-north1-docker.pkg.dev/css-markuslippo-2023/exercise-cicd/courses-api:v1
